---

- name: Remove default debian packaged docker
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Install Docker
  apt:
    name: "{{ docker_pkg_name }}"
    state: "{{ docker_pkg_state }}"
    update_cache: true
